# 謝辞

<!--# Acknowledgements-->

<!--
Writing this book was (and still is) a lot of fun.
But it is also a lot of work and I am very happy about the support I received.
-->

この本を書くのはとても楽しかったです（そして今でもそうです）。
しかし大変な作業でもあり、サポートしていただいたことにはとても満足しています。

<!--
My biggest thank-you goes to Katrin who had the hardest job in terms of hours and effort:
she proofread the book from beginning to end and discovered many spelling mistakes and inconsistencies that I would never have found.
I am very grateful for her support.
-->

時間的にも労力的にも一番大変な仕事をしてくれた Katrin には一番感謝しています。
彼女は最初から最後まで本を構成してくれて私が見つけられなかったであろうスペルミスや矛盾をたくさん見つけてくれました。
彼女には大変お世話になりました。

<!--
A big thanks goes to Verena Haunschmid for writing the section about [LIME explanations for images](#images-lime).
She works in data science and I recommend following her on Twitter: [\@ExpectAPatronum](https://twitter.com/ExpectAPatronum).
I also want to thank all the [early readers who contributed corrections](https://github.com/christophM/interpretable-ml-book/graphs/contributors) on Github!
-->

[画像データに対するLIME](#images-lime)の章について書いてくださった Verena Haunschmid に感謝します。
彼女はデータサイエンスの仕事をしていて、Twitter で彼女をフォロー([\@ExpectAPatronum](https://twitter.com/ExpectAPatronum))することをお勧めします。
また、Github 上に[修正を投稿してくれた初期の読者](https://github.com/christophM/interpretable-ml-book/graphs/contributors)に感謝します！

<!--
Furthermore, I want to thank everyone who created illustrations:
The cover was designed by my friend [\@YvonneDoinel](https://twitter.com/YvonneDoinel).
The graphics in the [Shapley Value chapter](#shapley) were created by [Heidi Seibold](https://twitter.com/HeidiBaya), as well as the turtle example in the [adversarial examples chapter](#adversarial).
Verena Haunschmid created the graphic in the [RuleFit chapter](#rulefit).
-->

さらに、イラストを作成してくださった皆様に感謝したいと思います。
表紙は友人 [\@YvonneDoinel](https://twitter.com/YvonneDoinel) によるもので、[シャープレイ値の章](#shapley)と[敵対的サンプルの章](#adversarial)の亀の例は [Heidi Seibold](https://twitter.com/HeidiBaya) 、[RuleFitの章](#rulefit)は Verena Haunschmid が作成してくれました。

<!--
In at least three aspects, the way I published this book is unconventional.
First, it is available both as website and as ebook/pdf.
The software I used to create this book is called `bookdown`, written by [Yihui Xie](https://yihui.name/), who created many R packages that make it easy to combine R code and text.
Thanks a lot!
Secondly, I self-publish the book on the platform [Leanpub](https://leanpub.com/), instead of working with a traditional publisher.
And third, I published the book as in-progress book, which has helped me enormously to get feedback and to monetize it along the way.
Many thanks to leanpub for making this possible and handling the royalties fairly.
I would also like to thank you, dear reader, for reading this book without a big publisher name behind it.
-->

少なくとも3つの面で、私がこの本を出版した方法は型破りです。
第一に、Webサイトや電子書籍、PDFでも入手可能です。
この本を作るのに使用したソフトウェアは、Rとテキストを簡単に多く組み合わせることができるRパッケージを多く作成している [Yihui Xie](https://yihui.name/) が書いた `bookdown` と呼ばれるソフトウェアです。
ありがとうございました！
第二に、従来の出版社ではなく、[Leanpub](https://leanpub.com/) というプラットフォームで本を自費出版しました。
第三に、私はこの本を執筆中の本として出版しましたが、そのおかげでフィードバックを得て、途中で収益化できました。
また、親愛なる読者の皆様、大きな出版社名なしのこの本を読んでくださったことに感謝します。

<!--
I am grateful for the funding of my research on interpretable machine learning by the Bavarian State Ministry of Science and the Arts in the framework of the Centre Digitisation.Bavaria (ZD.B).
-->
バイエレン州科学芸術省の Digitisation.Bavaria (ZD.B) の枠組みの中で、私の解釈可能な機械学習の研究に資金を提供してくれたことに感謝しています。
